[package]
name = "mpv-stt-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
mpv-stt-common.workspace = true
aes-gcm.workspace = true
sha2.workspace = true
rand.workspace = true
